# Generated by Django 4.2 on 2023-05-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Professions',
        ),
    ]
