# Generated by Django 4.2 on 2023-05-02 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0002_rename_category_professions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professions',
            options={'ordering': ('name',), 'verbose_name_plural': 'Professions'},
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('professions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='worker.professions')),
            ],
        ),
    ]
