# Generated by Django 4.2 on 2023-05-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_professions_options_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('profession',)},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='professions',
            new_name='profession',
        ),
    ]
