# Generated by Django 4.2 on 2023-05-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, height_field='250px', null=True, upload_to='members_images', width_field='370px'),
        ),
    ]
