# Generated by Django 4.2 on 2023-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
