# Generated by Django 4.2 on 2023-05-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='worker',
            new_name='member',
        ),
    ]
