# Generated by Django 4.2 on 2023-05-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_rename_worker_conversation_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='member',
            new_name='worker',
        ),
    ]
