# Generated by Django 4.2 on 2023-05-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0008_alter_conversationmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(default=False),
        ),
    ]
